services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: ["make", "dev"]
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
